Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,10 +20,12 @@ jobs:
 
     - name: Add SSH host key
       run: |
-          mkdir -p ~/.ssh
-          ssh-keyscan -H 52.66.20.249 > ~/.ssh/known_hosts
-          cat ~/.ssh/known_hosts
-
+        mkdir -p ~/.ssh
+        ssh-keyscan -H 52.66.20.249 > ~/.ssh/known_hosts
+        ls -la ~/.ssh
+        echo "Contents of known_hosts:"
+        cat ~/.ssh/known_hosts || echo "Failed to read known_hosts
+      
     - name: Deploy files to server
       run: |
         rsync -avz --delete-after --exclude='.git' ./ ubuntu@52.66.20.249:/var/www/html/LoginForm/
